### ISSUE TITLE
Could not load WebDAV contacts

### ISSUE THREAD

**Issue by mtk64** [somedevelopment/CardDAVSyncOutlook#8]
getting the following results and there is no import to Outlook 2010:

13:37:48 - Start
13:37:48 - Load last Sync UIDs
13:37:53 - Outlook opened
13:37:53 - WebDav Connection generated
...
13:38:20 - Load WebDav Contact Petr, Matulik
13:38:20 - Load WebDav Contact null, null
13:38:20 - Could not load WebDAV contacts
13:38:20 - Outlook closed

**Comment by abika** [comment]
Thanks for reporting. First, what version are you using?
And can you run the Java app from commandline:

    $ java -jar CardDAVSyncOutlook.jar
and post the output here? Looks like an exception, my guess is its related to specific contacts.

**Comment by mtk64** [comment]
Hello (oder Hallo, wir sind glaube ich beide Deutsche J)

 

I am using CardDAVSyncOutlook_v0.03, Windows 8.1, and MS Office 2010.

 

Here is the output:

 

C:\Users\Micha\Downloads\CardDAVSyncOutlook_v0.03>java -jar CardDAVSyncOutlook.jar

Error: Unable to access jarfile CardDAVSyncOutlook.jar

 

That was not working ;-) used exe instead …

 

 

C:\Users\Micha\Downloads\CardDAVSyncOutlook_v0.03>java -jar CardDAVSyncOutlook.exe

[Thread-3] [WARN] org.apache.commons.httpclient.HttpMethodBase - Cookie rejected

: "$Version=0; ocbc2a414d6b=llb8unf0g8sl8ek2onannmcm05; $Path=/owncloud". Illega

l path attribute "/owncloud". Path of origin: "//owncloud/remote.php/carddav/add

ressbooks/micha/kontakte"

[Thread-3] [INFO] org.apache.commons.httpclient.auth.AuthChallengeProcessor - ba

sic authentication scheme selected

[Thread-3] [WARN] org.apache.commons.httpclient.HttpMethodBase - Cookie rejected

: "$Version=0; ocbc2a414d6b=j513qvgup8bj682jvu07bru5h1; $Path=/owncloud". Illega

l path attribute "/owncloud". Path of origin: "//owncloud/remote.php/carddav/add

ressbooks/micha/kontakte"

[Thread-3] [WARN] org.apache.commons.httpclient.HttpMethodBase - Cookie rejected

: "$Version=0; ocbc2a414d6b=mv76110stktb8knd8ep15nksg6; $Path=/owncloud". Illega

l path attribute "/owncloud". Path of origin: "//owncloud/remote.php/carddav/add

ressbooks/micha/kontakte"

[Thread-3] [INFO] org.apache.commons.httpclient.auth.AuthChallengeProcessor - ba

sic authentication scheme selected

java.lang.NullPointerException

        at java.io.FileOutputStream.write(Unknown Source)

        at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:1

283)

        at contact.Contact.<init>(Contact.java:117)

        at webdav.ManageWebDAVContacts.loadContactsFromWebDav(ManageWebDAVContac

ts.java:188)

        at main.Userinterface$1.run(Userinterface.java:130)

        at java.lang.Thread.run(Unknown Source)

 

C:\Users\Micha\Downloads\CardDAVSyncOutlook_v0.03>

 

kind regards

Michael

 

Von: Alex [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Februar 2015 23:33
An: somedevelopment/CardDAVSyncOutlook
Cc: mtk64
Betreff: Re: [CardDAVSyncOutlook] Could not load WebDAV contacts (#8)

 

Thanks for reporting. First, what version are you using?
And can you run the Java app from commandline:

$ java -jar CardDAVSyncOutlook.jar

and post the output here? Looks like an exception, my guess is its related to specific contacts.

**Comment by abika** [comment]
Thanks again (or dankeschön). There was indeed a problem with photos in VCard contacts. Didn't test this but should be fixed.
I'll do some additional changes and then it's high time for a next release...

Fixed by 57739235a82a5a0cfbf4f3a76c33ebac1c03b678.

**Comment by mtk64** [comment]
That is great. Thank you in advance.
Wollen wir auf Deutsch weitermachen oder lieber beim Englisch bleiben?
Dann ein schönes Wochenende...

Mit freundlichen Grüßen aus der Schweiz 
Michael Klein

**Comment by abika** [comment]
[Check this out](https://github.com/somedevelopment/CardDAVSyncOutlook/releases/tag/Version_0.04)

> Wollen wir auf Deutsch weitermachen oder lieber beim Englisch bleiben?

always English, other people might wanna know what where are discussing.

**Comment by mtk64** [comment]
Oh, that´s true, forgot that.
